export type AppConfig = {
  serviceName: string;
  appEnv: string;
  port: number;
  jwtSecret: string;
  jwtAccessTokenTtl?: string;
  kafkaBrokers: string[];
  internalServiceToken?: string;
  userServiceBaseUrl?: string;
  userServiceTimeoutMs?: number;
  tomorrowServiceBaseUrl?: string;
  tomorrowServiceTimeoutMs?: number;
  tomorrowSchoolBaseUrl?: string;
  tomorrowSchoolAuthEndpoint?: string;
  tomorrowSchoolTimeoutMs?: number;
  tomorrowSchoolReferrer?: string;
  tomorrowSchoolXJwtToken?: string;
  tomorrowSchoolSessionId?: string;
  tomorrowSchoolGraphQlEndpoint?: string;
  tomorrowSchoolGraphQlRole?: string;
  tomorrowSchoolProfilePath?: string;
  mongodbUri?: string;
  mongodbDatabase?: string;
  redisUrl?: string;
  tomorrowJwtTtlSeconds?: number;
  logLevel?: string;
};
