package worker

import (
	"encoding/json"
	"fmt"
	"strings"
	"unicode"
)

func buildQuestionGenerationPrompt(analysis json.RawMessage) string {
	payload := strings.TrimSpace(string(analysis))
	if payload == "" {
		payload = "{}"
	}

	return `# Agent 8: Runtime AI Question Generator Agent

## Purpose

This is not a coding agent task for the current platform implementation.

This agent will run inside the platform service later.

It belongs to the AI analysis / exam generation service.

Its job is to analyze the user's Gitea repository, not the platform backend repository itself.

The generated questions are used in the offline Friday exam to verify whether the user really understands their own project code.

## Important Scope Rule

Analyze the user's Gitea repository only.

Do not generate questions about:
- this platform backend
- this platform frontend
- this AI service code
- this prompt
- the exam system itself

Only generate questions about the repository described by the input analysis.

## Input Context

The repository analysis may include:
- Repository file tree
- Important source files
- Entry points
- Route files
- Handler files
- Service files
- Database files
- Frontend pages
- Hooks
- Stores
- Components
- README summary
- Code summaries from previous AI agents

Use this input to generate questions about the user's actual codebase behavior.

## Task

Generate exactly 20 English-only multiple-choice questions based on the user's Gitea repository analysis.

The questions must test whether the user understands how their program actually works.

## Responsibilities

- Generate exactly 20 questions.
- Questions must be in English only.
- Each question must have A/B/C/D options.
- Only one answer can be correct.
- Include correct_option.
- Include explanation.
- Include difficulty.
- Include source_file_path.
- Focus on functional code understanding.
- Avoid shallow metadata questions.

## Question Focus

Questions should test functional understanding, for example:
- What happens when this API endpoint is called?
- Which function registers the route?
- How does this handler parse request data?
- Which service function owns this logic?
- What would break if this middleware is removed?
- Where should a new feature be added?
- How does data move from request to response?
- How does database access work?
- How does frontend state move from hook/store to component?
- How does a page section combine smaller components?
- How is net/http, mux, router, controller, or handler used?
- How does the program start?
- Which file controls this behavior?
- Which module owns this responsibility?

## Good Question Style

Good:
"In this user's repository, what happens when the POST /tasks endpoint is called?"

Good:
"Which layer is responsible for validating the request body before creating a record?"

Good:
"How does the frontend component receive data from the hook before rendering the list?"

Good:
"If the authentication middleware is removed from this route group, what behavior would change?"

Good:
"Where should a developer add a new repository-reading feature based on the current module structure?"

## Bad Question Style

Do not ask:
- What is the repository name?
- What language is used?
- What is the README title?
- What package version is used?
- What exact variable name appears in the file?
- How many files are in the repository?
- Who created the project?
- What is the name of this platform?
- How does the exam service work?

## Required JSON Output

Return JSON only. No markdown. No explanation outside JSON.

{
  "questions": [
    {
      "question": "In this user's repository, how are HTTP routes connected to handlers?",
      "options": {
        "A": "Routes are automatically generated from file names.",
        "B": "Routes are manually registered using mux.HandleFunc or a similar router setup.",
        "C": "Routes are loaded from the database at runtime.",
        "D": "Routes are generated by the frontend before each request."
      },
      "correct_option": "B",
      "explanation": "The provided repository code shows that routes are manually connected to handler functions in the router setup file.",
      "difficulty": "medium",
      "source_file_path": "internal/server/router.go"
    }
  ]
}

## Final Rules

- Return exactly 20 items in questions.
- Use the nested options object with keys A, B, C, and D.
- correct_option must be exactly one of A, B, C, or D.
- difficulty should be easy, medium, or hard.
- source_file_path must point to a file from the user's repository analysis.
- Every question must be answerable from the supplied repository analysis.
- Do not invent routes, files, components, stores, or behavior that are not supported by the analysis.
- Do not mention this platform, the AI service, or the exam system in any question.

Repository analysis:
` + payload
}

func parseAndValidateQuestions(raw json.RawMessage) ([]GeneratedQuestion, error) {
	var envelope questionEnvelope
	if err := json.Unmarshal(raw, &envelope); err != nil {
		return nil, err
	}
	if len(envelope.Questions) != 20 {
		return nil, fmt.Errorf("AI output must include exactly 20 questions, got %d", len(envelope.Questions))
	}

	questions := make([]GeneratedQuestion, 0, len(envelope.Questions))
	for i, item := range envelope.Questions {
		q := item.toGeneratedQuestion()
		if err := validateGeneratedQuestion(i+1, &q); err != nil {
			return nil, err
		}
		questions = append(questions, q)
	}
	return questions, nil
}

type questionEnvelope struct {
	Questions []questionOutput `json:"questions"`
}

type questionOutput struct {
	Question       string            `json:"question"`
	Options        map[string]string `json:"options"`
	OptionA        string            `json:"option_a"`
	OptionB        string            `json:"option_b"`
	OptionC        string            `json:"option_c"`
	OptionD        string            `json:"option_d"`
	CorrectOption  string            `json:"correct_option"`
	Explanation    string            `json:"explanation"`
	Difficulty     string            `json:"difficulty"`
	SourceFilePath string            `json:"source_file_path"`
}

func (q questionOutput) toGeneratedQuestion() GeneratedQuestion {
	optionA := q.OptionA
	optionB := q.OptionB
	optionC := q.OptionC
	optionD := q.OptionD
	if q.Options != nil {
		optionA = q.Options["A"]
		optionB = q.Options["B"]
		optionC = q.Options["C"]
		optionD = q.Options["D"]
	}
	return GeneratedQuestion{
		Question:       strings.TrimSpace(q.Question),
		OptionA:        strings.TrimSpace(optionA),
		OptionB:        strings.TrimSpace(optionB),
		OptionC:        strings.TrimSpace(optionC),
		OptionD:        strings.TrimSpace(optionD),
		CorrectOption:  strings.ToUpper(strings.TrimSpace(q.CorrectOption)),
		Explanation:    strings.TrimSpace(q.Explanation),
		Difficulty:     strings.ToLower(strings.TrimSpace(q.Difficulty)),
		SourceFilePath: strings.TrimSpace(q.SourceFilePath),
	}
}

func validateGeneratedQuestion(position int, q *GeneratedQuestion) error {
	if strings.TrimSpace(q.Question) == "" || strings.TrimSpace(q.OptionA) == "" || strings.TrimSpace(q.OptionB) == "" || strings.TrimSpace(q.OptionC) == "" || strings.TrimSpace(q.OptionD) == "" || strings.TrimSpace(q.Explanation) == "" || strings.TrimSpace(q.SourceFilePath) == "" {
		return fmt.Errorf("question %d is missing required fields", position)
	}
	if q.CorrectOption != "A" && q.CorrectOption != "B" && q.CorrectOption != "C" && q.CorrectOption != "D" {
		return fmt.Errorf("question %d correct_option must be A, B, C, or D", position)
	}
	if q.Difficulty != "easy" && q.Difficulty != "medium" && q.Difficulty != "hard" {
		return fmt.Errorf("question %d difficulty must be easy, medium, or hard", position)
	}
	if containsNonEnglishText(q.Question + q.OptionA + q.OptionB + q.OptionC + q.OptionD + q.Explanation) {
		return fmt.Errorf("question %d contains non-English text", position)
	}
	return nil
}

func containsNonEnglishText(s string) bool {
	for _, r := range s {
		if r > unicode.MaxASCII && (unicode.IsLetter(r) || unicode.Is(unicode.Han, r) || unicode.Is(unicode.Hiragana, r) || unicode.Is(unicode.Katakana, r) || unicode.Is(unicode.Hangul, r)) {
			return true
		}
	}
	return false
}
