package question

import (
	"context"
	"errors"
	"testing"
)

type fakeStore struct {
	questions []Question
	mappings  []ExamQuestionOption
}

func (f *fakeStore) EnsureSchema(context.Context) error { return nil }
func (f *fakeStore) SaveGeneratedQuestions(_ context.Context, analysisJobID string, questions []Question) (int, error) {
	f.questions = questions
	return len(questions), nil
}
func (f *fakeStore) GetQuestionsByAnalysisJob(context.Context, string, string) ([]Question, error) {
	if len(f.questions) == 0 {
		return nil, ErrNotFound
	}
	return f.questions, nil
}
func (f *fakeStore) GetQuestionsByExam(context.Context, string, string) ([]Question, error) {
	if len(f.questions) == 0 {
		return nil, ErrNotFound
	}
	return f.questions, nil
}
func (f *fakeStore) GetQuestionsByExamForInternal(context.Context, string) ([]Question, error) {
	if len(f.questions) == 0 {
		return nil, ErrNotFound
	}
	return f.questions, nil
}
func (f *fakeStore) GetExamOptionMappings(context.Context, string) ([]ExamQuestionOption, error) {
	return f.mappings, nil
}
func (f *fakeStore) SaveExamOptionMappings(_ context.Context, _ string, mappings []ExamQuestionOption) error {
	f.mappings = mappings
	return nil
}

func TestSaveGeneratedQuestionsRequiresExactlyTwenty(t *testing.T) {
	svc := NewService(&fakeStore{})
	_, err := svc.SaveGeneratedQuestions(context.Background(), SaveGeneratedQuestionsRequest{AnalysisJobID: "00000000-0000-0000-0000-000000000001"})
	var appErr *AppError
	if !errors.As(err, &appErr) {
		t.Fatalf("expected AppError, got %T", err)
	}
	if appErr.Code != ErrCodeBadRequest {
		t.Fatalf("expected %s, got %s", ErrCodeBadRequest, appErr.Code)
	}
}

func TestExamQuestionsHideAnswersAndStoreOptionMapping(t *testing.T) {
	store := &fakeStore{questions: []Question{{
		ID:             "00000000-0000-0000-0000-000000000010",
		AnalysisJobID:  "00000000-0000-0000-0000-000000000001",
		Question:       "How are routes connected?",
		OptionA:        "Automatically from filenames.",
		OptionB:        "Manually in router setup.",
		OptionC:        "Loaded from database.",
		OptionD:        "Generated by frontend.",
		CorrectOption:  OptionB,
		Explanation:    "The router setup connects paths to handlers.",
		Difficulty:     DifficultyMedium,
		SourceFilePath: "internal/server/router.go",
	}}}
	svc := NewService(store)

	resp, err := svc.GetExamQuestions(context.Background(), "00000000-0000-0000-0000-000000000001", "00000000-0000-0000-0000-000000000020")
	if err != nil {
		t.Fatalf("GetExamQuestions returned error: %v", err)
	}
	if len(resp.Questions) != 1 {
		t.Fatalf("expected one question, got %d", len(resp.Questions))
	}
	if resp.ExamID != "00000000-0000-0000-0000-000000000020" {
		t.Fatalf("exam id = %q", resp.ExamID)
	}
	if resp.QuestionsCount != 1 {
		t.Fatalf("questions count = %d", resp.QuestionsCount)
	}
	if resp.Questions[0].SourceFilePath != "" {
		t.Fatalf("exam response must not include source_file_path, got %q", resp.Questions[0].SourceFilePath)
	}
	if len(store.mappings) != 4 {
		t.Fatalf("expected four option mappings, got %d", len(store.mappings))
	}
	if resp.ID != "00000000-0000-0000-0000-000000000020" || resp.ExamID != "00000000-0000-0000-0000-000000000020" || resp.QuestionsCount != 1 {
		t.Fatalf("expected exam metadata in response, got %+v", resp)
	}

	key, err := svc.GetAnswerKey(context.Background(), "00000000-0000-0000-0000-000000000020")
	if err != nil {
		t.Fatalf("GetAnswerKey returned error: %v", err)
	}
	if len(key.Answers) != 1 || key.Answers[0].CorrectOption == "" {
		t.Fatalf("expected mapped answer key, got %#v", key.Answers)
	}
}

func TestAnalysisJobQuestionsIncludeMetadata(t *testing.T) {
	store := &fakeStore{questions: []Question{{
		ID:             "00000000-0000-0000-0000-000000000010",
		AnalysisJobID:  "00000000-0000-0000-0000-000000000001",
		Question:       "How are routes connected?",
		OptionA:        "Automatically from filenames.",
		OptionB:        "Manually in router setup.",
		OptionC:        "Loaded from database.",
		OptionD:        "Generated by frontend.",
		CorrectOption:  OptionB,
		Explanation:    "The router setup connects paths to handlers.",
		Difficulty:     DifficultyMedium,
		SourceFilePath: "internal/server/router.go",
	}}}
	svc := NewService(store)

	resp, err := svc.GetQuestionsByAnalysisJob(context.Background(), "00000000-0000-0000-0000-000000000001", "00000000-0000-0000-0000-000000000001")
	if err != nil {
		t.Fatalf("GetQuestionsByAnalysisJob returned error: %v", err)
	}
	if resp.AnalysisJobID != "00000000-0000-0000-0000-000000000001" {
		t.Fatalf("analysis job id = %q", resp.AnalysisJobID)
	}
	if resp.QuestionsCount != 1 {
		t.Fatalf("questions count = %d", resp.QuestionsCount)
	}
	if resp.Questions[0].SourceFilePath == "" {
		t.Fatal("source_file_path should be included for analysis job questions")
	}
}

func TestAnalysisQuestionsIncludeAnalysisJobMetadata(t *testing.T) {
	store := &fakeStore{questions: []Question{{
		ID:             "00000000-0000-0000-0000-000000000010",
		AnalysisJobID:  "00000000-0000-0000-0000-000000000001",
		Question:       "How are routes connected?",
		OptionA:        "Automatically from filenames.",
		OptionB:        "Manually in router setup.",
		OptionC:        "Loaded from database.",
		OptionD:        "Generated by frontend.",
		CorrectOption:  OptionB,
		Explanation:    "The router setup connects paths to handlers.",
		Difficulty:     DifficultyMedium,
		SourceFilePath: "internal/server/router.go",
	}}}
	svc := NewService(store)

	resp, err := svc.GetQuestionsByAnalysisJob(context.Background(), "00000000-0000-0000-0000-000000000001", "00000000-0000-0000-0000-000000000001")
	if err != nil {
		t.Fatalf("GetQuestionsByAnalysisJob returned error: %v", err)
	}
	if resp.ID != "00000000-0000-0000-0000-000000000001" || resp.AnalysisJobID != "00000000-0000-0000-0000-000000000001" || resp.QuestionsCount != 1 {
		t.Fatalf("expected analysis metadata in response, got %+v", resp)
	}
}

func TestEnglishOnlyValidationRejectsMostlyNonLatinText(t *testing.T) {
	input := validGeneratedQuestion()
	input.Question = "这是一个中文问题这是一个中文问题"
	if err := validateGeneratedQuestion(input); err == nil {
		t.Fatal("expected non-Latin question text to be rejected")
	}
}

func validGeneratedQuestion() GeneratedQuestionInput {
	return GeneratedQuestionInput{
		Question: "How are routes connected?",
		Options: map[string]string{
			OptionA: "Automatically from filenames.",
			OptionB: "Manually in router setup.",
			OptionC: "Loaded from database.",
			OptionD: "Generated by frontend.",
		},
		CorrectOption:  OptionB,
		Explanation:    "The router setup connects paths to handlers.",
		Difficulty:     DifficultyMedium,
		SourceFilePath: "internal/server/router.go",
	}
}
